# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: urlhit.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'urlhit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0curlhit.proto\x12\x06urlhit\";\n\x06UrlHit\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x10\n\x08long_url\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t28\n\nLogService\x12*\n\x0bRegisterHit\x12\x0e.urlhit.UrlHit\x1a\x0b.urlhit.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'urlhit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_URLHIT']._serialized_start=24
  _globals['_URLHIT']._serialized_end=83
  _globals['_ACK']._serialized_start=85
  _globals['_ACK']._serialized_end=106
  _globals['_LOGSERVICE']._serialized_start=108
  _globals['_LOGSERVICE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
